id: P000178
initial_creation_type: ebook
source_metadata:
  title: ༄༅། །ཆོས་འཁོར་རིམ་པ་གསུམ་གྱི་དྭོགས་གཅོད་རྩ་བ་བཞུགས་སོ། །
  authors:
  - མཛད་པ་པོ། ཀུན་མཁྱེན་པདྨ་དཀར་པོ།
  layers:
  - book_title
  - author
  - chapter_title
  - tsawa
  - quotation
  id: KS-PK-09
web_metadata:
  title:
    en: A Root Text and Commentary on Clarifying Queries Relating to the Three Turnings
      of the Dharma Wheel
    bo: ཆོས་འཁོར་རིམ་པ་གསུམ་གྱི་དྭོགས་གཅོད་རྩ་བ་དང་འགྲེལ་པ་བཞུགས་སོ། །
  collection:
    en: Pema Karpo Series–  Book 9
    bo: ཀུན་མཁྱེན་གཞུང་འགྲེལ།–  དེབ། ༩
  author:
    en: Kunkhyen Pema Karpo
    bo: ཀུན་མཁྱེན་པདྨ་དཀར་པོ།
  pusblisher:
    en: Gautam Buddha Vihara
    bo: དོན་བརྒྱུད་དཔལ་ལྡན་འབྲུག་པ།
  sku: KS-PK-09
  category:
    en: ''
    bo: ''
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: KS-PK-09.epub
  description:
    en: ''
    bo: ''
